name: Deploy

on:
  push:
    branches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      runs:
        echo "SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i keyfile ubuntu@65.2.11.196 "sudo bash ~/deploy.sh"